export default function PredictionTable({
    predictions,
    adjusted
}) {

    if (!predictions?.length) {
        return null;
    }

    return (

        <div
            className="
bg-white
rounded-[32px]
border
border-slate-200
shadow-sm
p-8
mb-8
"
        >

            <div className="mb-8">

                <p
                    className="
uppercase
tracking-[0.25em]
text-blue-600
text-xs
font-semibold
mb-2
"
                >
                    Forecast Result
                </p>

                <h2
                    className="
text-3xl
font-bold
mb-3
"
                >
                    Forecast & Adjustment Analysis
                </h2>

                <p
                    className="
text-slate-500
"
                >
                    Statistical forecast generated by the
                    selected forecasting model and adjusted
                    using weekly demand patterns.
                </p>

            </div>

            <div
                className="
mb-8
rounded-2xl
bg-blue-50
border
border-blue-100
p-6
"
            >

                <h3
                    className="
font-semibold
text-blue-700
mb-3
"
                >
                    Interpretation Guide
                </h3>

                <div
                    className="
grid
grid-cols-1
md:grid-cols-2
gap-6
text-sm
"
                >

                    <div>

                        <p
                            className="
font-semibold
mb-2
"
                        >
                            Statistical Forecast
                        </p>

                        <p className="text-slate-600">
                            Pure forecast generated by the
                            selected forecasting method
                            before any adjustment.
                        </p>

                    </div>

                    <div>

                        <p
                            className="
font-semibold
mb-2
"
                        >
                            Adjusted Forecast
                        </p>

                        <p className="text-slate-600">
                            Forecast after applying
                            weekly demand pattern
                            correction factors.
                        </p>

                    </div>

                </div>

            </div>

            <div className="overflow-x-auto">

                <table className="w-full">

                    <thead>

                        <tr className="border-b">

                            <th className="text-left py-4">
                                Date
                            </th>

                            <th className="text-left py-4">
                                Day
                            </th>

                            <th className="text-right py-4">
                                Statistical Forecast
                            </th>

                            <th className="text-right py-4">
                                Factor
                            </th>

                            <th className="text-right py-4">
                                Adjusted Forecast
                            </th>

                        </tr>

                    </thead>

                    <tbody>

                        {(adjusted || []).map(
                            (row, index) => (

                                <tr
                                    key={index}
                                    className="border-b"
                                >

                                    <td className="py-4">
                                        {row.date}
                                    </td>

                                    <td className="py-4">
                                        {row.day}
                                    </td>

                                    <td
                                        className="
py-4
text-right
font-medium
"
                                    >
                                        {row.base_qty}
                                    </td>

                                    <td
                                        className="
py-4
text-right
"
                                    >
                                        {row.factor}
                                    </td>

                                    <td
                                        className="
py-4
text-right
font-bold
text-blue-600
"
                                    >
                                        {row.qty}
                                    </td>

                                </tr>

                            )
                        )}

                    </tbody>

                </table>

            </div>

        </div>

    );

}